version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: server.py
      DATABASE_URL: postgres://postgres:password@db:5432/appdb
    depends_on:
      db:
        condition: service_healthy
    command: flask run --host=0.0.0.0
