version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres  # Using postgres as the user
      POSTGRES_PASSWORD: apppassword  # Set the corresponding password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Health check for the PostgreSQL user
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    environment:
      - FLASK_APP=server.py
      - DATABASE_URL=postgres://postgres:apppassword@db:5432/appdb  # Using postgres as the user
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
