version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapping Flask's port to host
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase  # Database connection string
    command: flask run --host=0.0.0.0  # Run the Flask app
    depends_on:
      db:
        condition: service_healthy  # Wait for the database to be healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]  # Simple health check on Flask app
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mydatabase -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
