version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      FLASK_APP: server.py
      DATABASE_URL: postgres://postgres:password@db:5432/appdb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  db_data:
