version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    command: ["./wait-for-postgres.sh", "db", "flask", "run", "--host=0.0.0.0"]  # Added 'db' here to pass the service name to the script
    environment:
      - FLASK_APP=server.py
      - DATABASE_URL=postgres://postgres:password@db:5432/appdb
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy  # Ensures the app waits for the database to be healthy before starting

volumes:
  db_data:
