version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres  # Keeping the user as postgres
      POSTGRES_PASSWORD: apppassword  # Set the corresponding password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Updated to check the correct user
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    environment:
      - FLASK_APP=server.py
      - DATABASE_URL=postgres://postgres:apppassword@db:5432/appdb  # Updated to use postgres
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
